//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilderNET.DataAccess.ServiceObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesFilder : DbContext
    {
        public EntitiesFilder()
            : base("name=EntitiesFilder")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_JERARQUIA> TBL_JERARQUIA { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
        public virtual DbSet<TBL_FOLIOS> TBL_FOLIOS { get; set; }
        public virtual DbSet<TBL_ARCHIVO_GLOBAL> TBL_ARCHIVO_GLOBAL { get; set; }
        public virtual DbSet<TBL_COMISION_PROMOTOR> TBL_COMISION_PROMOTOR { get; set; }
        public virtual DbSet<TBL_GLOBAL> TBL_GLOBAL { get; set; }
        public virtual DbSet<TBL_NET_FACTURA> TBL_NET_FACTURA { get; set; }
        public virtual DbSet<TBL_NET_HISTORICO_FACTURA> TBL_NET_HISTORICO_FACTURA { get; set; }
        public virtual DbSet<TBL_LOG> TBL_LOG { get; set; }
        public virtual DbSet<TBL_NET_BONO> TBL_NET_BONO { get; set; }
        public virtual DbSet<TBL_NET_BONO_HISTORICO> TBL_NET_BONO_HISTORICO { get; set; }
    }
}
