//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilderNET.DataAccess.ServiceObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GLOBAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_GLOBAL()
        {
            this.TBL_ARCHIVO_GLOBAL = new HashSet<TBL_ARCHIVO_GLOBAL>();
        }
    
        public int ID_GLOBAL { get; set; }
        public Nullable<int> ID_PROMOTOR { get; set; }
        public Nullable<System.DateTime> FECHA_ELABORACION { get; set; }
        public string FILDER { get; set; }
        public Nullable<System.DateTime> FECHA_CAPTURA { get; set; }
        public string MESA_CONTROL { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string TEL_CONTACTO { get; set; }
        public string SERVICIO { get; set; }
        public string TIPO { get; set; }
        public string PAQUETE { get; set; }
        public string FOLIO_SIAC { get; set; }
        public string PAGO_A_PROMOTOR { get; set; }
        public Nullable<bool> ESTATUS_PAGO_INGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO_INGRESO { get; set; }
        public Nullable<bool> ESTATUS_PAGO_POSTEO { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO_POSTEO { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<bool> ESTATUS_PAGO_INGRESO_LIDER { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO_INGRESO_LIDER { get; set; }
        public Nullable<bool> ESTATUS_PAGO_POSTEO_LIDER { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO_POSTEO_LIDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ARCHIVO_GLOBAL> TBL_ARCHIVO_GLOBAL { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
