//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilderNET.DataAccess.ServiceObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ARCHIVO_GLOBAL
    {
        public int ID_ARCHIVO_GLOBAL { get; set; }
        public Nullable<int> ID_GLOBAL { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
        public string EXT { get; set; }
        public string RUTA { get; set; }
    
        public virtual TBL_GLOBAL TBL_GLOBAL { get; set; }
    }
}
