//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilderNET.DataAccess.ServiceObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COMISION_PROMOTOR
    {
        public int ID_COMISION_PROMOTOR { get; set; }
        public string SERVICIO { get; set; }
        public string TIPO { get; set; }
        public string PAQUETE { get; set; }
        public Nullable<double> COMISION { get; set; }
    }
}
