//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilderNET.DataAccess.ServiceObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NET_FACTURA
    {
        public int ID_FACTURA { get; set; }
        public Nullable<System.DateTime> QUINCENA { get; set; }
        public string FOLIO_SIAC { get; set; }
        public Nullable<double> IMPORTE_BASE { get; set; }
        public Nullable<double> IMPORTE_POSTEO { get; set; }
        public string PISA_E { get; set; }
        public string PROCEDE2 { get; set; }
        public string PAGO2 { get; set; }
        public string FECHA { get; set; }
        public string OS_PAGO { get; set; }
        public string ESTATUS { get; set; }
        public string LINEA_CONTRATADA { get; set; }
        public string PAQUETE { get; set; }
    }
}
